title: NonymA Blog
description: 실험, 자동화, 시도들에 대한 요약
author: NonymA

theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# ensure Jekyll processes custom pages directory
include:
  - "_pages"


collections:
  tmp-review:
    output: true
